### PR TITLE
Allow positioning to PhysicsPolygon

### PR DESCRIPTION
**Pull request by loicgillioz**
Parameter position was always set to zero

### CODE REVIEW

**Comment by pmudry** [comment]
Please resubmit with a new constructor. If you change the existing one, everyone who's using this code will have to adapt.

**Comment by pmudry** [comment]
Accepted, thank you for your input.

**Comment by metc** [comment]
Please guys, use the `develop` branch for PR and not the `master`, see [CONTRIBUTING](https://github.com/hevs-isi/gdx2d/blob/master/CONTRIBUTING.md).

**Comment by pmudry** [comment]
OMG, you just created a *Spaghetti monster". It just became *very* complicated to update the lib for the students and provide them with a new version. For instance, I was not able to compile the lib as a jar for the student despite my 10 minutes effort.... pfff... :sweat:

**Pull request merged**
