### PR TITLE
Controllers extension feature

### PR DESCRIPTION
**Pull request by metc**
This PR contains a basic interface to work with the `controllers` extensions of libgdx (related to #131).
A basic demo can be used to check if the controller is detected or not, and print some information when buttons are pressed and sliders are moved. In order to use the`DemoControllers`, you have to compile the `core` and `desktop` projects.

Current implementation state:
 1. I have only tested the demo with the XBox One controller.
 2. The callbacks `` and `` are not called. We must poll the state of the controllers to known when it is connected or not.
 3. The buttons and sliders codes of the XBox controller are not the same on each OS. I changes some codes for Windows, but not for all platforms yet.

By merging this in the `develop` branch, we will have a snapshot version ready for the students interested in using a controller.

### CODE REVIEW

**Comment by metc** [comment]
@RandomReaper @pmudry please review :notes:

**Comment by RandomReaper** [comment]
I have little hope getting this controller supported in the current DR0x setup.

The problem is:
* This controller require a new kernel
* new kernel -> new graphic driver
* new graphic driver -> new opengl library
* new opengl library -> ...

In brief a lot of work and it will be supported in the next DR0x setup, and re-testing almost all
inf1 (and probably others) labs.

I won't do that unless @pmudry ask me...

**Comment by pmudry** [comment]
Come on !

Why not that ? http://pingus.seul.org/~grumbel/xboxdrv/

**Comment by RandomReaper** [comment]
I would like to test but I'm lost in the dependencies.
I am probably between maven and eclipse or just around /dev/null

**Comment by RandomReaper** [comment]
somewhat working on ubuntu 16.04

**Comment by metc** [comment]
Let's see how it works in DR0x. Please download the latest snapshot version from here and replace it in the demo-desktop project.

https://oss.sonatype.org/content/repositories/snapshots/ch/hevs/gdx2d/gdx2d-desktop/1.2.2-SNAPSHOT/

**Comment by RandomReaper** [comment]
I will test this kernel-mode driver today : https://github.com/paroj/xpad

**Pull request merged**
